version: 0.2

phases:
  pre_build:
    commands:
      - echo Connecting to Amazon ECR...
      - aws --version
      # - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      # - aws ecr get-login-password --region us-east-2 | docker login
      #   --username AWS --password-stdin
      #   916495840179.dkr.ecr.us-east-2.amazonaws.com
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 167693783846.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=167693783846.dkr.ecr.us-east-2.amazonaws.com/cicd-node-sample
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      # - docker build --platform linux/amd64 -t $REPOSITORY_URI:latest .
      - docker build -t cicd-node-sample .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"simple-app","imageUri":"%s"}]'
        $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
