apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::167693783846:role/eksctl-cicd-node-sample-nodegroup-NodeInstanceRole-CZ2T8M85VHZQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::167693783846:role/service-role/codebuild-cicd-sample-service-role
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::167693783846:user/admin
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-08T03:19:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "56869"
  uid: e7908dd7-c4ae-41b9-81ab-0bc0d4993a47
