apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cicd-node-sample
  name: cicd-node-sample-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cicd-node-sample
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cicd-node-sample
    spec:
      containers:
      - image: CONTAINER_IMAGE
        imagePullPolicy: Always
        name: cicd-node-sample
        ports:
        - containerPort: 3000